x-common: &common
  volumes:
    - .:/app/script
  working_dir: /app/script
  command: python openformat-to-obj.py ./test_assets/*

services:
  python3.7:
    <<: *common
    image: python:3.7-slim

  python3.8:
    <<: *common
    image: python:3.8-slim

  python3.9:
    <<: *common
    image: python:3.9-slim

  python3.10:
    <<: *common
    image: python:3.10-slim

  python3.11:
    <<: *common
    image: python:3.11-slim

  python3.12:
    <<: *common
    image: python:3.12-slim
